### ISSUE TITLE
Return URL

### ISSUE THREAD

**Issue by towoju5** [vanilophp/stripe#1]
Please How do i add a return url on a successful payment?
Below is how i called the payment endpoint.  or better still if i can redirect user to Stripe website for checkout and have a return_url/success_url setup as we have in the regular stripe session integration.

```
        $paymentMethod = PaymentMethod::find($request->get('paymentMethod'));
        $payment = PaymentFactory::createFromPayable($order, $paymentMethod);
        $gateway = PaymentGateways::make($paymentMethod->gateway);
        $paymentRequest = $gateway->createPaymentRequest($payment);
```

I was able to implement the Stripe form on the website but after the payment it shows a successful payment notification but won't redirect.

**Comment by fulopattila122** [comment]
I need to take a look at it. This module hasn't been finalized yet, but this part (return URL generation) has been generalized already across other Vanilo Payment gateway implementations, so I think we can solve this quickly.

I will come back on this soon.

**Comment by towoju5** [comment]
Thanks for the hard work on this. I really enjoyed the framework.

**Comment by fulopattila122** [comment]
Sorry for the slow response, here we go:

```php
$gateway->createPaymentRequest($payment, null, ['return_url' => 'https://your.return.url']);
```

The second, `null` parameter can be null or a shipping address object.

**Comment by fulopattila122** [comment]
With the 2.1 version of the module, you can configure the return URL in the configuration instead of passing it as an option:

- either set the `STRIPE_RETURN_URL` in .env
- or set the `vanilo.stripe.return_url` config directly, which the module will pick up and handle.
